
development:
  adapter: mysql2
  host: localhost
  database: db/saveseat-development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: localhost
  database: db/saveseat-test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  database: db/saveseat-production
  username: root
  password: root
  pool: 5
  timeout: 5000