# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

countries = Country.create([{ name: 'Afghanistan' },
{ name: 'Albania' },
{ name: 'Algeria' },
{ name: 'Andorra' },
{ name: 'Angola' },
{ name: 'Antigua & Deps' },
{ name: 'Argentina' },
{ name: 'Armenia' },
{ name: 'Australia' },
{ name: 'Austria' },
{ name: 'Azerbaijan' },
{ name: 'Bahamas' },
{ name: 'Bahrain' },
{ name: 'Bangladesh' },
{ name: 'Barbados' },
{ name: 'Belarus' },
{ name: 'Belgium' },
{ name: 'Belize' },
{ name: 'Benin' },
{ name: 'Bhutan' },
{ name: 'Bolivia' },
{ name: 'Bosnia Herzegovina' },
{ name: 'Botswana' },
{ name: 'Brazil' },
{ name: 'Brunei' },
{ name: 'Bulgaria' },
{ name: 'Burkina' },
{ name: 'Burundi' },
{ name: 'Cambodia' },
{ name: 'Cameroon' },
{ name: 'Canada' },
{ name: 'Cape Verde' },
{ name: 'Central African Rep' },
{ name: 'Chad' },
{ name: 'Chile' },
{ name: 'China' },
{ name: 'Colombia' },
{ name: 'Comoros' },
{ name: 'Congo' },
{ name: 'Congo {Democratic Rep}' },
{ name: 'Costa Rica' },
{ name: 'Croatia' },
{ name: 'Cuba' },
{ name: 'Cyprus' },
{ name: 'Czech Republic' },
{ name: 'Denmark' },
{ name: 'Djibouti' },
{ name: 'Dominica' },
{ name: 'Dominican Republic' },
{ name: 'East Timor' },
{ name: 'Ecuador' },
{ name: 'Egypt' },
{ name: 'El Salvador' },
{ name: 'Equatorial Guinea' },
{ name: 'Eritrea' },
{ name: 'Estonia' },
{ name: 'Ethiopia' },
{ name: 'Fiji' },
{ name: 'Finland' },
{ name: 'France' },
{ name: 'Gabon' },
{ name: 'Gambia' },
{ name: 'Georgia' },
{ name: 'Germany' },
{ name: 'Ghana' },
{ name: 'Greece' },
{ name: 'Grenada' },
{ name: 'Guatemala' },
{ name: 'Guinea' },
{ name: 'Guinea-Bissau' },
{ name: 'Guyana' },
{ name: 'Haiti' },
{ name: 'Honduras' },
{ name: 'Hungary' },
{ name: 'Iceland' },
{ name: 'India' },
{ name: 'Indonesia' },
{ name: 'Iran' },
{ name: 'Iraq' },
{ name: 'Ireland {Republic}' },
{ name: 'Israel' },
{ name: 'Italy' },
{ name: 'Ivory Coast' },
{ name: 'Jamaica' },
{ name: 'Japan' },
{ name: 'Jordan' },
{ name: 'Kazakhstan' },
{ name: 'Kenya' },
{ name: 'Kiribati' },
{ name: 'Korea North' },
{ name: 'Korea South' },
{ name: 'Kosovo' },
{ name: 'Kuwait' },
{ name: 'Kyrgyzstan' },
{ name: 'Laos' },
{ name: 'Latvia' },
{ name: 'Lebanon' },
{ name: 'Lesotho' },
{ name: 'Liberia' },
{ name: 'Libya' },
{ name: 'Liechtenstein' },
{ name: 'Lithuania' },
{ name: 'Luxembourg' },
{ name: 'Macedonia' },
{ name: 'Madagascar' },
{ name: 'Malawi' },
{ name: 'Malaysia' },
{ name: 'Maldives' },
{ name: 'Mali' },
{ name: 'Malta' },
{ name: 'Marshall Islands' },
{ name: 'Mauritania' },
{ name: 'Mauritius' },
{ name: 'Mexico' },
{ name: 'Micronesia' },
{ name: 'Moldova' },
{ name: 'Monaco' },
{ name: 'Mongolia' },
{ name: 'Montenegro' },
{ name: 'Morocco' },
{ name: 'Mozambique' },
{ name: 'Myanmar, {Burma}' },
{ name: 'Namibia' },
{ name: 'Nauru' },
{ name: 'Nepal' },
{ name: 'Netherlands' },
{ name: 'New Zealand' },
{ name: 'Nicaragua' },
{ name: 'Niger' },
{ name: 'Nigeria' },
{ name: 'Norway' },
{ name: 'Oman' },
{ name: 'Pakistan' },
{ name: 'Palau' },
{ name: 'Panama' },
{ name: 'Papua New Guinea' },
{ name: 'Paraguay' },
{ name: 'Peru' },
{ name: 'Philippines' },
{ name: 'Poland' },
{ name: 'Portugal' },
{ name: 'Qatar' },
{ name: 'Romania' },
{ name: 'Russian Federation' },
{ name: 'Rwanda' },
{ name: 'St Kitts & Nevis' },
{ name: 'St Lucia' },
{ name: 'Saint Vincent & the Grenadines' },
{ name: 'Samoa' },
{ name: 'San Marino' },
{ name: 'Sao Tome & Principe' },
{ name: 'Saudi Arabia' },
{ name: 'Senegal' },
{ name: 'Serbia' },
{ name: 'Seychelles' },
{ name: 'Sierra Leone' },
{ name: 'Singapore' },
{ name: 'Slovakia' },
{ name: 'Slovenia' },
{ name: 'Solomon Islands' },
{ name: 'Somalia' },
{ name: 'South Africa' },
{ name: 'Spain' },
{ name: 'Sri Lanka' },
{ name: 'Sudan' },
{ name: 'Suriname' },
{ name: 'Swaziland' },
{ name: 'Sweden' },
{ name: 'Switzerland' },
{ name: 'Syria' },
{ name: 'Taiwan' },
{ name: 'Tajikistan' },
{ name: 'Tanzania' },
{ name: 'Thailand' },
{ name: 'Togo' },
{ name: 'Tonga' },
{ name: 'Trinidad & Tobago' },
{ name: 'Tunisia' },
{ name: 'Turkey' },
{ name: 'Turkmenistan' },
{ name: 'Tuvalu' },
{ name: 'Uganda' },
{ name: 'Ukraine' },
{ name: 'United Arab Emirates' },
{ name: 'United Kingdom' },
{ name: 'United States' },
{ name: 'Uruguay' },
{ name: 'Uzbekistan' },
{ name: 'Vanuatu' },
{ name: 'Vatican City' },
{ name: 'Venezuela' },
{ name: 'Vietnam' },
{ name: 'Yemen' },
{ name: 'Zambia' },
{ name: 'Zimbabwe' }])


states = State.create([{ country_id: 186, name: 'Alabama' },
{ country_id: 186, name: 'Alaska' },
{ country_id: 186, name: 'Arizona' },
{ country_id: 186, name: 'Arkansas' },
{ country_id: 186, name: 'California' },
{ country_id: 186, name: 'Colorado' },
{ country_id: 186, name: 'Connecticut' },
{ country_id: 186, name: 'Delaware' },
{ country_id: 186, name: 'District Of Columbia' },
{ country_id: 186, name: 'Florida' },
{ country_id: 186, name: 'Georgia' },
{ country_id: 186, name: 'Hawaii' },
{ country_id: 186, name: 'Idaho' },
{ country_id: 186, name: 'Illinois' },
{ country_id: 186, name: 'Indiana' },
{ country_id: 186, name: 'Iowa' },
{ country_id: 186, name: 'Kansas' },
{ country_id: 186, name: 'Kentucky' },
{ country_id: 186, name: 'Louisiana' },
{ country_id: 186, name: 'Maine' },
{ country_id: 186, name: 'Maryland' },
{ country_id: 186, name: 'Massachusetts' },
{ country_id: 186, name: 'Michigan' },
{ country_id: 186, name: 'Minnesota' },
{ country_id: 186, name: 'Mississippi' },
{ country_id: 186, name: 'Missouri' },
{ country_id: 186, name: 'Montana' },
{ country_id: 186, name: 'Nebraska' },
{ country_id: 186, name: 'Nevada' },
{ country_id: 186, name: 'New Hampshire' },
{ country_id: 186, name: 'New Jersey' },
{ country_id: 186, name: 'New Mexico' },
{ country_id: 186, name: 'New York' },
{ country_id: 186, name: 'North Carolina' },
{ country_id: 186, name: 'North Dakota' },
{ country_id: 186, name: 'Ohio' },
{ country_id: 186, name: 'Oklahoma' },
{ country_id: 186, name: 'Oregon' },
{ country_id: 186, name: 'Pennsylvania' },
{ country_id: 186, name: 'Rhode Island' },
{ country_id: 186, name: 'South Carolina' },
{ country_id: 186, name: 'South Dakota' },
{ country_id: 186, name: 'Tennessee' },
{ country_id: 186, name: 'Texas' },
{ country_id: 186, name: 'Utah' },
{ country_id: 186, name: 'Vermont' },
{ country_id: 186, name: 'Virginia' },
{ country_id: 186, name: 'Washington' },
{ country_id: 186, name: 'West Virginia' },
{ country_id: 186, name: 'Wisconsin' },
{ country_id: 186, name: 'Wyoming' }])

cities = City.create([{ country_id: 186, state_id:1, name: 'Montgomery' },
{ country_id: 186, state_id:2, name: 'Juneau' },
{ country_id: 186, state_id:3, name: 'Phoenix' },
{ country_id: 186, state_id:4, name: 'Little Rock' },
{ country_id: 186, state_id:5, name: 'Sacramento' },
{ country_id: 186, state_id:6, name: 'Denver' },
{ country_id: 186, state_id:7, name: 'Hartford' },
{ country_id: 186, state_id:8, name: 'Dover' },
{ country_id: 186, state_id:9, name: 'Tallahassee' },
{ country_id: 186, state_id:10, name: 'Atlanta' },
{ country_id: 186, state_id:11, name: 'Honolulu' },
{ country_id: 186, state_id:12, name: 'Boise' },
{ country_id: 186, state_id:13, name: 'Springfield' },
{ country_id: 186, state_id:14, name: 'Indianapolis' },
{ country_id: 186, state_id:15, name: 'Des Moines' },
{ country_id: 186, state_id:16, name: 'Topeka' },
{ country_id: 186, state_id:17, name: 'Frankfort' },
{ country_id: 186, state_id:18, name: 'Baton Rouge' },
{ country_id: 186, state_id:19, name: 'Augusta' },
{ country_id: 186, state_id:20, name: 'Annapolis' },
{ country_id: 186, state_id:21, name: 'Boston' },
{ country_id: 186, state_id:22, name: 'Lansing' },
{ country_id: 186, state_id:23, name: 'St. Paul' },
{ country_id: 186, state_id:24, name: 'Jackson' },
{ country_id: 186, state_id:25, name: 'Jefferson City' },
{ country_id: 186, state_id:26, name: 'Helena' },
{ country_id: 186, state_id:27, name: 'Lincoln' },
{ country_id: 186, state_id:28, name: 'Carson City' },
{ country_id: 186, state_id:29, name: 'Concord' },
{ country_id: 186, state_id:30, name: 'Trenton' },
{ country_id: 186, state_id:31, name: 'Santa Fe' },
{ country_id: 186, state_id:32, name: 'Albany' },
{ country_id: 186, state_id:33, name: 'Raleigh' },
{ country_id: 186, state_id:34, name: 'Bismarck' },
{ country_id: 186, state_id:35, name: 'Columbus' },
{ country_id: 186, state_id:36, name: 'Oklahoma City' },
{ country_id: 186, state_id:37, name: 'Salem' },
{ country_id: 186, state_id:38, name: 'Harrisburg' },
{ country_id: 186, state_id:39, name: 'Providence' },
{ country_id: 186, state_id:40, name: 'Columbia' },
{ country_id: 186, state_id:41, name: 'Pierre' },
{ country_id: 186, state_id:42, name: 'Nashville' },
{ country_id: 186, state_id:43, name: 'Austin' },
{ country_id: 186, state_id:44, name: 'Salt Lake City' },
{ country_id: 186, state_id:45, name: 'Montpelier' },
{ country_id: 186, state_id:46, name: 'Richmond' },
{ country_id: 186, state_id:47, name: 'Olympia' },
{ country_id: 186, state_id:48, name: 'Charleston' },
{ country_id: 186, state_id:49, name: 'Madison' },
{ country_id: 186, state_id:50, name: 'Cheyenne' }])

